version: "3.8"
services:
    lams:
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - 80:8080
            - 9990:9990
        volumes:
            - ./:/app2
        env_file: .env
        environment:
            DBHOST: '83.212.78.59'
            DBNAME: lams_v4
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8181:80
        environment:
            PMA_HOST: '83.212.78.59'
            MYSQL_USERNAME: lams_docker_setup_user